# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "1.0.3.dev17+g170ef26.d20230328"
__version_tuple__ = version_tuple = (1, 0, 3, "dev17", "g170ef26.d20230328")
